import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/mode-toggle";
import { AppProvider } from "./AppProvider";
import { cookies } from "next/headers";
import { checkExpireRefresh, getExpireFromJWT } from "@/lib/utils";
import SlideSession from "@/components/slide-sessison";

const inter = Inter({
    subsets: ["vietnamese"],
    weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookiesStore = await cookies();
    const token = cookiesStore.get("sessionToken");
    const expiresAtSession = cookiesStore.get("expiresAtSession");

    return (
        <html
            suppressHydrationWarning
            lang="en"
            className={`${inter.className} h-full antialiased`}
        >
            <body className="min-h-full w-full flex flex-col flex-1 items-center justify-center bg-zinc-50 font-sans dark:bg-black">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <AppProvider
                        initSessionToken={token?.value || ""}
                        initExpires={expiresAtSession?.value || ""}
                    >
                        <ModeToggle />
                        {children}
                        <SlideSession />
                    </AppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
